#!/bin/bash

# Get the directory of the current script
SCRIPT_DIR=$(dirname "$(realpath "$0")")

HOOK_PATH="$SCRIPT_DIR/../.git/.hooks/pre-commit"

add_precommit_hook() {
    local _hook_path="$1"
    local _command="$2"

    if [ -f "$_hook_path" ]; then
        if ! grep -Fxq "$_command" "$_hook_path"; then
            echo "$_command" >> "$_hook_path"
        fi
    else
        create_precommit_hook_file "$_hook_path"
        echo "$_command" >> "$_hook_path"
    fi
}

create_precommit_hook_file() {
    local _hook_path="$1"

    echo '#!/bin/bash' > "$_hook_path"
    echo >> "$_hook_path"
    chmod +x "$_hook_path"
}

add_precommit_hook "$HOOK_PATH" "../../.hooks/ktfmt"
