#!/bin/bash

if [ $# -lt 2 ]; then
    # Less than two arguments provided, use null
    value=null
else
    # Second argument provided, use it as the value
    value=$2
fi

curl --request PUT 'localhost:8080/shortlinks/update/url' \
-H 'Content-Type: application/json' \
-d "{\"username\":\"prashant\", \"code\": \"$1\", \"url\":\"$2\"}"
